# The Docker image that will be used to build your app
image: python:alpine
# Functions that should be executed before the build script is run
before_script:
  - pip install markdown
pages:
  script:
    - python -m markdown README.md > index.html
    - mkdir public
    - find . -maxdepth 1 -mindepth 1 -not -name public -not -name '.*' | xargs -I{} mv {} public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
    expire_in: 90 days
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
